version: '3'

networks:
  default:

services:

  tallink-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tallink-backend
    ports:
      - 8819:8819
      - 9090:9090
    networks:
      - default
